Resources:
  SingleTableDesignDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: datastore-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
